id: PDB1ED394
initial_creation_type: input
source_metadata:
  title: Rigdzin Gödem
  language: bo
  description: 'Texts by and about Rigdzin Gödem Ngödrup Gyaltsen (rig ''dzin rgod
    ldem dngos grub rgyal mtshan, 1337–1408), famed discoverer of the so-called Northern
    Treasures (byang gter) revelation:'
  volume:
    8583a891208d4c56ae85c62a24b08169:
      title: The Powerful Prayer of Aspiration from the Tantra of the Great Perfection
        that Reveals the All-Penetrating Wisdom Mind of Samantabhadra (Kunzang Mönlam)
      parent: Aspiration Prayers
    901e122ab1ac445a8084a2c7d92db031:
      title: 'Le''u Dünma—Chapter 1: The Prayer to the Three Kāya Guru'
      parent: Le'u Dünma
    c97db6127df74894a364b3d64c8f2fa0:
      title: 'Le''u Dünma—Chapter 2: The Prayer Requested by King Tri Songdetsen'
      parent: Le'u Dünma
    d12491c439e240c7ab66a4298291080f:
      title: 'Le''u Dünma—Chapter 3: The Prayer Requested by Khandro Yeshe Tsogyal'
      parent: Le'u Dünma
    f5201c041c1a49bfaacbb5c643d7a8b1:
      title: 'Le''u Dünma—Chapter 4: The Prayer Requested by Namkhe Nyingpo'
      parent: Le'u Dünma
    fc5e3ee9466646c4b4d4fdb3d377bc96:
      title: 'Le''u Dünma—Chapter 5: The Prayer Requested by Nanam Dorje Dudjom'
      parent: Le'u Dünma
    c31b5d61dd524ca8971cffa8242d95f5:
      title: 'Le''u Dünma—Chapter 6: The Prayer Requested by Prince Mutri Tsenpo'
      parent: Le'u Dünma
    8c9ce43fc9884f8d80457f41eaa2b9d3:
      title: Le'u Dünma—Chapter 7. The Prayer to Guru Rinpoche that Spontaneously
        Fulfills All Wishes (Sampa Lhundrupma)
      parent: Le'u Dünma
    1cc07f72f66e48399323857c46b23ae4:
      title: The Means for Accomplishment called the Blazing Wheel
      parent: Practices
    2a4a1c2397714d10a7b32e401f49c518:
      title: 'The Wish-Fulfilling Jewel: A Daily Sādhana of the Noble Avalokiteśvara'
      parent: Sādhanas
created_at: '2022-03-01T01:21:42.535752'
last_modified_at: '2022-03-01T01:21:42.535755'
